import { lazy } from "react";
import type { PermissionCode } from "@britium/shared";

export type RouteDef = {
  path: string;
  label: string;
  element: ReturnType<typeof lazy>;
  requireAuth: boolean;
  requiredPermissions?: PermissionCode[];
};

export const ROUTES: RouteDef[] = [
  {
    path: "/",
    label: "Index",
    element: lazy(() => import("@/pages/home/Index")),
    requireAuth: false,
  },
  {
    path: "/admin/audit",
    label: "Audit Logs",
    element: lazy(() => import("@/pages/AuditLogs")),
    requireAuth: true,
    requiredPermissions: ["ADM:AUDIT_LOGS:VIEW:S5_COMPANY"],
  },
  {
    path: "/admin/dashboard",
    label: "Admin Dashboard",
    element: lazy(() => import("@/pages/AdminDashboard")),
    requireAuth: true,
    requiredPermissions: ["ADM:ADMIN_DASHBOARD:VIEW:S5_COMPANY"],
  },
  {
    path: "/admin/permission-assignment",
    label: "Permission Assignment",
    element: lazy(() => import("@/pages/PermissionAssignment")),
    requireAuth: true,
    requiredPermissions: ["ADM:PERMISSION_ASSIGNMENT:VIEW:S5_COMPANY"],
  },
  {
    path: "/admin/supervisor-audit",
    label: "Supervisor Audit",
    element: lazy(() => import("@/pages/SupervisorAudit")),
    requireAuth: true,
    requiredPermissions: ["ADM:SUPERVISOR_AUDIT:VIEW:S5_COMPANY"],
  },
  {
    path: "/admin/users",
    label: "Admin Users",
    element: lazy(() => import("@/pages/AdminUsers")),
    requireAuth: true,
    requiredPermissions: ["ADM:ADMIN_USERS:VIEW:S5_COMPANY"],
  },
  {
    path: "/analytics/analytics",
    label: "Analytics",
    element: lazy(() => import("@/pages/Analytics")),
    requireAuth: true,
    requiredPermissions: ["ANA:ANALYTICS:VIEW:S4_REGION"],
  },
  {
    path: "/calculator",
    label: "Calculator",
    element: lazy(() => import("@/pages/Calculator")),
    requireAuth: true,
    requiredPermissions: ["OPS:CALCULATOR:VIEW:S3_BRANCH"],
  },
  {
    path: "/customer/customer-portal",
    label: "Customer Portal",
    element: lazy(() => import("@/pages/CustomerPortal")),
    requireAuth: true,
    requiredPermissions: ["CUS:CUSTOMER_PORTAL:VIEW:S1_SELF"],
  },
  {
    path: "/customer/customer-support",
    label: "Customer Support",
    element: lazy(() => import("@/pages/customer/CustomerSupport")),
    requireAuth: true,
    requiredPermissions: ["CUS:CUSTOMER_SUPPORT:VIEW:S1_SELF"],
  },
  {
    path: "/dashboard",
    label: "Dashboard",
    element: lazy(() => import("@/pages/Dashboard")),
    requireAuth: true,
    requiredPermissions: ["OPS:DASHBOARD:VIEW:S3_BRANCH"],
  },
  {
    path: "/execution/courier-app",
    label: "Courier App",
    element: lazy(() => import("@/pages/CourierApp")),
    requireAuth: true,
    requiredPermissions: ["EXEC:COURIER_APP:VIEW:S3_BRANCH"],
  },
  {
    path: "/execution/delivery",
    label: "Delivery",
    element: lazy(() => import("@/pages/Delivery")),
    requireAuth: true,
    requiredPermissions: ["EXEC:DELIVERY:VIEW:S3_BRANCH"],
  },
  {
    path: "/execution/delivery-flow",
    label: "Delivery Flow",
    element: lazy(() => import("@/pages/rider/DeliveryFlow")),
    requireAuth: true,
    requiredPermissions: ["EXEC:DELIVERY_FLOW:VIEW:S3_BRANCH"],
  },
  {
    path: "/execution/electronic-signature-management",
    label: "Electronic Signature Management",
    element: lazy(() => import("@/pages/ElectronicSignatureManagement")),
    requireAuth: true,
    requiredPermissions: ["EXEC:ELECTRONIC_SIGNATURE_MANAGEMENT:VIEW:S3_BRANCH"],
  },
  {
    path: "/execution/label-activation",
    label: "Label Activation",
    element: lazy(() => import("@/pages/rider/LabelActivation")),
    requireAuth: true,
    requiredPermissions: ["EXEC:LABEL_ACTIVATION:VIEW:S3_BRANCH"],
  },
  {
    path: "/execution/parcel-pickup",
    label: "Parcel Pickup",
    element: lazy(() => import("@/pages/ParcelPickup")),
    requireAuth: true,
    requiredPermissions: ["EXEC:PARCEL_PICKUP:VIEW:S3_BRANCH"],
  },
  {
    path: "/execution/pickup-flow",
    label: "Pickup Flow",
    element: lazy(() => import("@/pages/rider/PickupFlow")),
    requireAuth: true,
    requiredPermissions: ["EXEC:PICKUP_FLOW:VIEW:S3_BRANCH"],
  },
  {
    path: "/execution/rider-calculator",
    label: "Rider Calculator",
    element: lazy(() => import("@/pages/RiderCalculator")),
    requireAuth: true,
    requiredPermissions: ["EXEC:RIDER_CALCULATOR:VIEW:S3_BRANCH"],
  },
  {
    path: "/execution/rider-dashboard",
    label: "Rider Dashboard",
    element: lazy(() => import("@/pages/RiderDashboard")),
    requireAuth: true,
    requiredPermissions: ["EXEC:RIDER_DASHBOARD:VIEW:S3_BRANCH"],
  },
  {
    path: "/execution/rider-delivery",
    label: "Rider Delivery",
    element: lazy(() => import("@/pages/RiderDelivery")),
    requireAuth: true,
    requiredPermissions: ["EXEC:RIDER_DELIVERY:VIEW:S3_BRANCH"],
  },
  {
    path: "/execution/rider-label",
    label: "Rider Label",
    element: lazy(() => import("@/pages/RiderLabel")),
    requireAuth: true,
    requiredPermissions: ["EXEC:RIDER_LABEL:VIEW:S3_BRANCH"],
  },
  {
    path: "/execution/rider-pickup",
    label: "Rider Pickup",
    element: lazy(() => import("@/pages/RiderPickup")),
    requireAuth: true,
    requiredPermissions: ["EXEC:RIDER_PICKUP:VIEW:S3_BRANCH"],
  },
  {
    path: "/execution/rider-tags",
    label: "Rider Tags",
    element: lazy(() => import("@/pages/RiderTags")),
    requireAuth: true,
    requiredPermissions: ["EXEC:RIDER_TAGS:VIEW:S3_BRANCH"],
  },
  {
    path: "/execution/shipping-calculator",
    label: "Shipping Calculator",
    element: lazy(() => import("@/pages/rider/ShippingCalculator")),
    requireAuth: true,
    requiredPermissions: ["EXEC:SHIPPING_CALCULATOR:VIEW:S3_BRANCH"],
  },
  {
    path: "/execution/tag-batch-management",
    label: "Tag Batch Management",
    element: lazy(() => import("@/pages/rider/TagBatchManagement")),
    requireAuth: true,
    requiredPermissions: ["EXEC:TAG_BATCH_MANAGEMENT:VIEW:S3_BRANCH"],
  },
  {
    path: "/execution/warehouse-drop",
    label: "Warehouse Drop",
    element: lazy(() => import("@/pages/rider/WarehouseDrop")),
    requireAuth: true,
    requiredPermissions: ["EXEC:WAREHOUSE_DROP:VIEW:S3_BRANCH"],
  },
  {
    path: "/finance",
    label: "Finance",
    element: lazy(() => import("@/pages/Finance")),
    requireAuth: true,
    requiredPermissions: ["FIN:FINANCE:VIEW:S4_REGION"],
  },
  {
    path: "/finance/reports",
    label: "Reports",
    element: lazy(() => import("@/pages/Reports")),
    requireAuth: true,
    requiredPermissions: ["FIN:REPORTS:VIEW:S4_REGION"],
  },
  {
    path: "/finance/revenue-forecast",
    label: "Revenue Forecast",
    element: lazy(() => import("@/pages/RevenueForecast")),
    requireAuth: true,
    requiredPermissions: ["FIN:REVENUE_FORECAST:VIEW:S4_REGION"],
  },
  {
    path: "/fleet",
    label: "Fleet",
    element: lazy(() => import("@/pages/Fleet")),
    requireAuth: true,
    requiredPermissions: ["GPS:FLEET:VIEW:S3_BRANCH"],
  },
  {
    path: "/fleet/gps-tracking",
    label: "GPS Tracking Dashboard",
    element: lazy(() => import("@/pages/GPSTrackingDashboard")),
    requireAuth: true,
    requiredPermissions: ["GPS:GPS_TRACKING_DASHBOARD:VIEW:S3_BRANCH"],
  },
  {
    path: "/fleet/live-map",
    label: "Real Time Map View",
    element: lazy(() => import("@/pages/RealTimeMapView")),
    requireAuth: true,
    requiredPermissions: ["GPS:REAL_TIME_MAP_VIEW:VIEW:S3_BRANCH"],
  },
  {
    path: "/merchant/merchant-analytics",
    label: "Merchant Analytics",
    element: lazy(() => import("@/pages/MerchantAnalytics")),
    requireAuth: true,
    requiredPermissions: ["MER:MERCHANT_ANALYTICS:VIEW:S1_SELF"],
  },
  {
    path: "/merchant/merchant-portal",
    label: "Merchant Portal",
    element: lazy(() => import("@/pages/MerchantPortal")),
    requireAuth: true,
    requiredPermissions: ["MER:MERCHANT_PORTAL:VIEW:S1_SELF"],
  },
  {
    path: "/operations/advanced-logistics",
    label: "Advanced Logistics",
    element: lazy(() => import("@/pages/AdvancedLogistics")),
    requireAuth: true,
    requiredPermissions: ["OPS:ADVANCED_LOGISTICS:VIEW:S3_BRANCH"],
  },
  {
    path: "/operations/approval-queue",
    label: "Approval Queue",
    element: lazy(() => import("@/pages/ApprovalQueue")),
    requireAuth: true,
    requiredPermissions: ["OPS:APPROVAL_QUEUE:VIEW:S3_BRANCH"],
  },
  {
    path: "/operations/audit-dashboard",
    label: "Audit Dashboard",
    element: lazy(() => import("@/pages/supervisor/AuditDashboard")),
    requireAuth: true,
    requiredPermissions: ["OPS:AUDIT_DASHBOARD:VIEW:S3_BRANCH"],
  },
  {
    path: "/operations/campaign-manager",
    label: "Campaign Manager",
    element: lazy(() => import("@/pages/marketing/CampaignManager")),
    requireAuth: true,
    requiredPermissions: ["MKT:CAMPAIGN_MANAGER:VIEW:S5_COMPANY"],
  },
  {
    path: "/operations/control-room",
    label: "Control Room",
    element: lazy(() => import("@/pages/ControlRoom")),
    requireAuth: true,
    requiredPermissions: ["OPS:CONTROL_ROOM:VIEW:S3_BRANCH"],
  },
  {
    path: "/operations/data-entry",
    label: "Data Entry",
    element: lazy(() => import("@/pages/DataEntry")),
    requireAuth: true,
    requiredPermissions: ["OPS:DATA_ENTRY:VIEW:S3_BRANCH"],
  },
  {
    path: "/operations/enterprise-portal",
    label: "Enterprise Portal",
    element: lazy(() => import("@/pages/EnterprisePortal")),
    requireAuth: true,
    requiredPermissions: ["OPS:ENTERPRISE_PORTAL:VIEW:S3_BRANCH"],
  },
  {
    path: "/operations/home",
    label: "Home",
    element: lazy(() => import("@/pages/Home")),
    requireAuth: true,
    requiredPermissions: ["OPS:HOME:VIEW:S3_BRANCH"],
  },
  {
    path: "/operations/human-resources",
    label: "Human Resources",
    element: lazy(() => import("@/pages/HumanResources")),
    requireAuth: true,
    requiredPermissions: ["HR:HUMAN_RESOURCES:VIEW:S5_COMPANY"],
  },
  {
    path: "/operations/landing-page",
    label: "Landing Page",
    element: lazy(() => import("@/pages/LandingPage")),
    requireAuth: true,
    requiredPermissions: ["OPS:LANDING_PAGE:VIEW:S3_BRANCH"],
  },
  {
    path: "/operations/manual-page",
    label: "Manual Page",
    element: lazy(() => import("@/pages/ManualPage")),
    requireAuth: true,
    requiredPermissions: ["OPS:MANUAL_PAGE:VIEW:S3_BRANCH"],
  },
  {
    path: "/operations/map",
    label: "Map",
    element: lazy(() => import("@/pages/Map")),
    requireAuth: true,
    requiredPermissions: ["GPS:MAP:VIEW:S3_BRANCH"],
  },
  {
    path: "/operations/marketing",
    label: "Marketing",
    element: lazy(() => import("@/pages/Marketing")),
    requireAuth: true,
    requiredPermissions: ["MKT:MARKETING:VIEW:S5_COMPANY"],
  },
  {
    path: "/operations/marketing-dashboard",
    label: "Marketing Dashboard",
    element: lazy(() => import("@/pages/marketing/MarketingDashboard")),
    requireAuth: true,
    requiredPermissions: ["MKT:MARKETING_DASHBOARD:VIEW:S5_COMPANY"],
  },
  {
    path: "/operations/operations",
    label: "Operations",
    element: lazy(() => import("@/pages/Operations")),
    requireAuth: true,
    requiredPermissions: ["OPS:OPERATIONS:VIEW:S3_BRANCH"],
  },
  {
    path: "/operations/pickup-request",
    label: "Pickup Request",
    element: lazy(() => import("@/pages/PickupRequest")),
    requireAuth: true,
    requiredPermissions: ["OPS:PICKUP_REQUEST:VIEW:S3_BRANCH"],
  },
  {
    path: "/operations/qr-code-management",
    label: "QRCode Management",
    element: lazy(() => import("@/pages/QRCodeManagement")),
    requireAuth: true,
    requiredPermissions: ["OPS:QR_CODE_MANAGEMENT:VIEW:S3_BRANCH"],
  },
  {
    path: "/operations/qr-operations",
    label: "QROperations",
    element: lazy(() => import("@/pages/QROperations")),
    requireAuth: true,
    requiredPermissions: ["OPS:QR_OPERATIONS:VIEW:S3_BRANCH"],
  },
  {
    path: "/operations/registration-queue",
    label: "Registration Queue",
    element: lazy(() => import("@/pages/RegistrationQueue")),
    requireAuth: true,
    requiredPermissions: ["OPS:REGISTRATION_QUEUE:VIEW:S3_BRANCH"],
  },
  {
    path: "/operations/role-management",
    label: "Role Management",
    element: lazy(() => import("@/pages/RoleManagement")),
    requireAuth: true,
    requiredPermissions: ["OPS:ROLE_MANAGEMENT:VIEW:S3_BRANCH"],
  },
  {
    path: "/operations/route-optimization-dashboard",
    label: "Route Optimization Dashboard",
    element: lazy(() => import("@/pages/RouteOptimizationDashboard")),
    requireAuth: true,
    requiredPermissions: ["OPS:ROUTE_OPTIMIZATION_DASHBOARD:VIEW:S3_BRANCH"],
  },
  {
    path: "/operations/settings",
    label: "Settings",
    element: lazy(() => import("@/pages/Settings")),
    requireAuth: true,
    requiredPermissions: ["OPS:SETTINGS:VIEW:S3_BRANCH"],
  },
  {
    path: "/operations/shipment-lifecycle",
    label: "Shipment Lifecycle",
    element: lazy(() => import("@/pages/ShipmentLifecycle")),
    requireAuth: true,
    requiredPermissions: ["OPS:SHIPMENT_LIFECYCLE:VIEW:S3_BRANCH"],
  },
  {
    path: "/operations/shipment-registration",
    label: "Shipment Registration",
    element: lazy(() => import("@/pages/office/ShipmentRegistration")),
    requireAuth: true,
    requiredPermissions: ["OPS:SHIPMENT_REGISTRATION:VIEW:S3_BRANCH"],
  },
  {
    path: "/operations/shipments",
    label: "Shipments",
    element: lazy(() => import("@/pages/Shipments")),
    requireAuth: true,
    requiredPermissions: ["OPS:SHIPMENTS:VIEW:S3_BRANCH"],
  },
  {
    path: "/operations/sign-up",
    label: "Sign Up",
    element: lazy(() => import("@/pages/SignUp")),
    requireAuth: true,
    requiredPermissions: ["OPS:SIGN_UP:VIEW:S3_BRANCH"],
  },
  {
    path: "/operations/submit-for-approval",
    label: "Submit For Approval",
    element: lazy(() => import("@/pages/SubmitForApproval")),
    requireAuth: true,
    requiredPermissions: ["OPS:SUBMIT_FOR_APPROVAL:VIEW:S3_BRANCH"],
  },
  {
    path: "/operations/substation",
    label: "Substation",
    element: lazy(() => import("@/pages/Substation")),
    requireAuth: true,
    requiredPermissions: ["OPS:SUBSTATION:VIEW:S3_BRANCH"],
  },
  {
    path: "/operations/substation-receiving",
    label: "Substation Receiving",
    element: lazy(() => import("@/pages/substation/SubstationReceiving")),
    requireAuth: true,
    requiredPermissions: ["OPS:SUBSTATION_RECEIVING:VIEW:S3_BRANCH"],
  },
  {
    path: "/operations/supervisor-dashboard",
    label: "Supervisor Dashboard",
    element: lazy(() => import("@/pages/SupervisorDashboard")),
    requireAuth: true,
    requiredPermissions: ["OPS:SUPERVISOR_DASHBOARD:VIEW:S3_BRANCH"],
  },
  {
    path: "/operations/system-settings",
    label: "System Settings",
    element: lazy(() => import("@/pages/SystemSettings")),
    requireAuth: true,
    requiredPermissions: ["OPS:SYSTEM_SETTINGS:VIEW:S3_BRANCH"],
  },
  {
    path: "/operations/tag-inventory-management",
    label: "Tag Inventory Management",
    element: lazy(() => import("@/pages/supervisor/TagInventoryManagement")),
    requireAuth: true,
    requiredPermissions: ["OPS:TAG_INVENTORY_MANAGEMENT:VIEW:S3_BRANCH"],
  },
  {
    path: "/operations/tracking-map",
    label: "Tracking Map",
    element: lazy(() => import("@/pages/TrackingMap")),
    requireAuth: true,
    requiredPermissions: ["GPS:TRACKING_MAP:VIEW:S3_BRANCH"],
  },
  {
    path: "/operations/tracking-map-page",
    label: "Tracking Map Page",
    element: lazy(() => import("@/pages/supervisor/TrackingMapPage")),
    requireAuth: true,
    requiredPermissions: ["OPS:TRACKING_MAP_PAGE:VIEW:S3_BRANCH"],
  },
  {
    path: "/operations/user-management",
    label: "User Management",
    element: lazy(() => import("@/pages/UserManagement")),
    requireAuth: true,
    requiredPermissions: ["OPS:USER_MANAGEMENT:VIEW:S3_BRANCH"],
  },
  {
    path: "/operations/users",
    label: "Users",
    element: lazy(() => import("@/pages/Users")),
    requireAuth: true,
    requiredPermissions: ["OPS:USERS:VIEW:S3_BRANCH"],
  },
  {
    path: "/support/customer-service-dashboard",
    label: "Customer Service Dashboard",
    element: lazy(() => import("@/pages/service/CustomerServiceDashboard")),
    requireAuth: true,
    requiredPermissions: ["SUP:CUSTOMER_SERVICE_DASHBOARD:VIEW:S3_BRANCH"],
  },
  {
    path: "/support/customer-support",
    label: "Customer Support",
    element: lazy(() => import("@/pages/CustomerSupport")),
    requireAuth: true,
    requiredPermissions: ["SUP:CUSTOMER_SUPPORT:VIEW:S3_BRANCH"],
  },
  {
    path: "/support/live-chat-interface",
    label: "Live Chat Interface",
    element: lazy(() => import("@/pages/service/LiveChatInterface")),
    requireAuth: true,
    requiredPermissions: ["SUP:LIVE_CHAT_INTERFACE:VIEW:S3_BRANCH"],
  },
  {
    path: "/warehouse/dispatch-management",
    label: "Dispatch Management",
    element: lazy(() => import("@/pages/warehouse/DispatchManagement")),
    requireAuth: true,
    requiredPermissions: ["WH:DISPATCH_MANAGEMENT:VIEW:S3_BRANCH"],
  },
  {
    path: "/warehouse/hub-operations",
    label: "Hub Operations",
    element: lazy(() => import("@/pages/HubOperations")),
    requireAuth: true,
    requiredPermissions: ["WH:HUB_OPERATIONS:VIEW:S3_BRANCH"],
  },
  {
    path: "/warehouse/receiving-bay",
    label: "Receiving Bay",
    element: lazy(() => import("@/pages/warehouse/ReceivingBay")),
    requireAuth: true,
    requiredPermissions: ["WH:RECEIVING_BAY:VIEW:S3_BRANCH"],
  },
  {
    path: "/warehouse/rider-warehouse",
    label: "Rider Warehouse",
    element: lazy(() => import("@/pages/RiderWarehouse")),
    requireAuth: true,
    requiredPermissions: ["WH:RIDER_WAREHOUSE:VIEW:S3_BRANCH"],
  },
  {
    path: "/warehouse/substation-receiving",
    label: "Substation Receiving",
    element: lazy(() => import("@/pages/SubstationReceiving")),
    requireAuth: true,
    requiredPermissions: ["WH:SUBSTATION_RECEIVING:VIEW:S3_BRANCH"],
  },
  {
    path: "/warehouse/supervisor-inventory",
    label: "Supervisor Inventory",
    element: lazy(() => import("@/pages/SupervisorInventory")),
    requireAuth: true,
    requiredPermissions: ["WH:SUPERVISOR_INVENTORY:VIEW:S3_BRANCH"],
  },
  {
    path: "/warehouse/warehouse",
    label: "Warehouse",
    element: lazy(() => import("@/pages/Warehouse")),
    requireAuth: true,
    requiredPermissions: ["WH:WAREHOUSE:VIEW:S3_BRANCH"],
  },
  {
    path: "/warehouse/warehouse-dispatch",
    label: "Warehouse Dispatch",
    element: lazy(() => import("@/pages/WarehouseDispatch")),
    requireAuth: true,
    requiredPermissions: ["WH:WAREHOUSE_DISPATCH:VIEW:S3_BRANCH"],
  },
  {
    path: "/warehouse/warehouse-operations",
    label: "Warehouse Operations",
    element: lazy(() => import("@/pages/WarehouseOperations")),
    requireAuth: true,
    requiredPermissions: ["WH:WAREHOUSE_OPERATIONS:VIEW:S3_BRANCH"],
  },
  {
    path: "/warehouse/warehouse-receiving",
    label: "Warehouse Receiving",
    element: lazy(() => import("@/pages/WarehouseReceiving")),
    requireAuth: true,
    requiredPermissions: ["WH:WAREHOUSE_RECEIVING:VIEW:S3_BRANCH"],
  },
];
